### ISSUE TITLE
McMMO integration error

### ISSUE THREAD

**Issue by Drdeceased** [2008Choco/VeinMiner#106]
Receiving repeating error when user uses VeinMiner with plugin McMMO enabled.
`[18:17:13 ERROR]: Could not pass event McMMOPlayerXpGainEvent to VeinMiner v2.1.1
java.lang.NoSuchMethodError: 'com.gmail.nossr50.datatypes.skills.PrimarySkillType com.gmail.nossr50.events.experience.McMMOPlayerXpGainEvent.getSkill()'
	at wtf.choco.veinminer.listener.McMMOIntegrationListener.onGainVeinMinerXP(McMMOIntegrationListener.java:24) ~[VeinMiner-Bukkit-2.1.1.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-405]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-405]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-405]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at com.gmail.nossr50.util.EventUtils.handleXpGainEvent(EventUtils.java:157) ~[mcMMO.jar:?]
	at com.gmail.nossr50.datatypes.player.McMMOPlayer.applyXpGain(McMMOPlayer.java:469) ~[mcMMO.jar:?]
	at com.gmail.nossr50.datatypes.player.McMMOPlayer.beginUnsharedXpGain(McMMOPlayer.java:437) ~[mcMMO.jar:?]
	at com.gmail.nossr50.datatypes.player.McMMOPlayer.beginXpGain(McMMOPlayer.java:427) ~[mcMMO.jar:?]
	at com.gmail.nossr50.skills.SkillManager.applyXpGain(SkillManager.java:32) ~[mcMMO.jar:?]
	at com.gmail.nossr50.skills.acrobatics.AcrobaticsManager.rollCheck(AcrobaticsManager.java:97) ~[mcMMO.jar:?]
	at com.gmail.nossr50.listeners.EntityListener.onEntityDamage(EntityListener.java:289) ~[mcMMO.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor43.execute(Unknown Source) ~[?:?]`

**Comment by 2008Choco** [comment]
What version of McMMO are you using? They must have changed their events recently.

**Comment by Drdeceased** [comment]
Sorry I should have included that information...
v2.0.0-SNAPSHOT
And yes it appears to be back under active development.

**Comment by 2008Choco** [comment]
I don't imagine this is something they necessarily want to "fix". Given the "2.0.0" versioning I can only assume they're just revamping their API, which is something I'll have to accommodate for. I'll keep this in mind. Thanks!

**Comment by 2008Choco** [comment]
Yeah. I think this is just an instance of McMMO being severely out of date. I'm sorry. I have no plans on supporting that old of a version.
