### ISSUE TITLE
LightAnticheat's latest version incompatible with VeinMiner.

### ISSUE THREAD

**Issue by RealTriassic** [2008Choco/VeinMiner#120]
Running LightAntiCheat 1.2.6.

```
[04:44:00 INFO]: [VeinMiner] Anti cheat detected. Enabling anti cheat support for "LightAntiCheat"
[04:44:00 ERROR]: [VeinMiner] The version of LightAntiCheat on this server is incompatible with Veinminer. Please post information on the spigot resource discussion page.
[04:44:00 WARN]: java.lang.ClassNotFoundException: vekster.lightanticheat.api.Utils
[04:44:00 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197)
[04:44:00 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[04:44:00 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[04:44:00 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[04:44:00 WARN]:        at java.base/java.lang.Class.forName(Class.java:534)
[04:44:00 WARN]:        at java.base/java.lang.Class.forName(Class.java:513)
[04:44:00 WARN]:        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68)
[04:44:00 WARN]:        at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source)
[04:44:00 WARN]:        at VeinMiner-2.2.4.jar//wtf.choco.veinminer.anticheat.AntiCheatHookLightAntiCheat.<init>(AntiCheatHookLightAntiCheat.java:28)
[04:44:00 WARN]:        at VeinMiner-2.2.4.jar//wtf.choco.veinminer.VeinMinerPlugin.lambda$onEnable$5(VeinMinerPlugin.java:163)
[04:44:00 WARN]:        at VeinMiner-2.2.4.jar//wtf.choco.veinminer.VeinMinerPlugin.registerAntiCheatHookIfEnabled(VeinMinerPlugin.java:413)
[04:44:00 WARN]:        at VeinMiner-2.2.4.jar//wtf.choco.veinminer.VeinMinerPlugin.onEnable(VeinMinerPlugin.java:163)
[04:44:00 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[04:44:00 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[04:44:00 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[04:44:00 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[04:44:00 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640)
[04:44:00 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589)
[04:44:00 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754)
[04:44:00 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516)
[04:44:00 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329)
[04:44:00 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215)
[04:44:00 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[04:44:00 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[04:44:00 WARN]: [VeinMiner] The installed version of "LightAntiCheat" is incompatible with VeinMiner. Please contact the author of VeinMiner.
```

**Comment by 2008Choco** [comment]
I thought LAC was abandoned. I'll have to take another look.
