### ISSUE TITLE
1.14 Support

### ISSUE THREAD

**Issue by goldmuskhex** [2008Choco/VeinMiner#20]
Hello,

It appears that 1.14 has broken Vein Miner.  Let me know if you need anymore information.

 
    ... 19 more
[15:27:27] [Server thread/ERROR]: Could not pass event BlockBreakEvent to VeinMiner v1.13.3
org.bukkit.event.EventException: null
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[minecraft_server.jar:git-Spigot-fa07878-c9fa596]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[minecraft_server.jar:git-Spigot-fa07878-c9fa596]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508) ~[minecraft_server.jar:git-Spigot-fa07878-c9fa596]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493) ~[minecraft_server.jar:git-Spigot-fa07878-c9fa596]
    at net.minecraft.server.v1_14_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:286) ~[minecraft_server.jar:git-Spigot-fa07878-c9fa596]
    at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:193) ~[minecraft_server.jar:git-Spigot-fa07878-c9fa596]
    at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1186) ~[minecraft_server.jar:git-Spigot-fa07878-c9fa596]
    at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[minecraft_server.jar:git-Spigot-fa07878-c9fa596]
    at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[minecraft_server.jar:git-Spigot-fa07878-c9fa596]
    at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[minecraft_server.jar:git-Spigot-fa07878-c9fa596]
    at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [minecraft_server.jar:git-Spigot-fa07878-c9fa596]
    at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [minecraft_server.jar:git-Spigot-fa07878-c9fa596]
    at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [minecraft_server.jar:git-Spigot-fa07878-c9fa596]
    at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [minecraft_server.jar:git-Spigot-fa07878-c9fa596]
    at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:892) [minecraft_server.jar:git-Spigot-fa07878-c9fa596]
    at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:885) [minecraft_server.jar:git-Spigot-fa07878-c9fa596]
    at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [minecraft_server.jar:git-Spigot-fa07878-c9fa596]
    at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:869) [minecraft_server.jar:git-Spigot-fa07878-c9fa596]
    at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:802) [minecraft_server.jar:git-Spigot-fa07878-c9fa596]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang3/EnumUtils
    at wtf.choco.veinminer.listener.BreakBlockListener.onBlockBreak(BreakBlockListener.java:61) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:311) ~[minecraft_server.jar:git-Spigot-fa07878-c9fa596]

**Comment by 2008Choco** [comment]
A release will be available today to resolve the incompatibility issues :)
