### ISSUE TITLE
VeinMiner crashing when starting 1.17 server

### ISSUE THREAD

**Issue by omega9380** [2008Choco/VeinMiner#59]
VM is crashing with a `java.lang.NullPointerException: Cannot invoke "java.lang.Class.getSimpleName()" because "clazz" is null` error when trying to start the server.  This occurs with the latest VM (1.17.7) and older versions (tried 1.17.6 and 1.17.5).

Server: `3109-Spigot-191e497-74575d4 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)`
Other running plugins:
```
ChestSort v10.0.4
LuckPerms 2814-v388301
```
Java: 
```
openjdk 16.0.1 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode, sharing)
```
Server Hardware info: 
```
OS: Ubuntu 21.04 x86_64
Host: NUC7i5DNHE J57828-514
Kernel: 5.11.0-18-generic
Uptime: 30 mins
Packages: 785 (dpkg), 4 (snap)
Shell: bash 5.1.4
Terminal: /dev/pts/3
CPU: Intel i5-7300U (4) @ 3.500GHz
GPU: Intel HD Graphics 620
Memory: 6755MiB / 15877MiB
```
Running CubeCoders AMP 2.1.1.8 as a backend management system

Error message:
```
09:35:38 Could not find class PlayerInteractManager
09:35:41 - Error occurred while enabling VeinMiner v1.17.7 (Is it up to date?)
09:35:41 - java.lang.NullPointerException: Cannot invoke "java.lang.Class.getSimpleName()" because "clazz" is null
                  at wtf.choco.veinminer.utils.ReflectionUtil.getField(ReflectionUtil.java:83) ~[?:?]
                  at wtf.choco.veinminer.utils.ReflectionUtil.init(ReflectionUtil.java:58) ~[?:?]
                  at wtf.choco.veinminer.VeinMiner.onEnable(VeinMiner.java:121) ~[?:?]
                  at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.17.jar:3109-Spigot-191e497-74575d4]
                  at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-1.17.jar:3109-Spigot-191e497-74575d4]
                  at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.17.jar:3109-Spigot-191e497-74575d4]
                  at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495) ~[spigot-1.17.jar:3109-Spigot-191e497-74575d4]
                  at org.bukkit.craftbukkit.v1_17_R1.CraftServ is:open er.enablePlugins(CraftServer.java:409) ~[spigot-1.17.jar:3109-Spigot-191e497-74575d4]
                  at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:607) ~[spigot-1.17.jar:3109-Spigot-191e497-74575d4]
                  at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264) ~[spigot-1.17.jar:3109-Spigot-191e497-74575d4]
                  at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:986) ~[spigot-1.17.jar:3109-Spigot-191e497-74575d4]
                  at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot-1.17.jar:3109-Spigot-191e497-74575d4]
                  at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by omega9380** [comment]
Never mind!  I inadvertantly had my Java version set to 11 instead of 16.  VM works now!

**Comment by omega9380** [comment]
Spoke too soon.  When I adjusted my Java version AMP chose Spigot 1.16.5.  Still getting the same errors on Java 16 and Spigot 1.17.

**Comment by 2008Choco** [comment]
Yep! This is still an issue. Unfortunately I can't really make a fix until there's a change in Bukkit, otherwise there will be plugin incompatibilities. I've made a change request and hopefully it should get merged within 24 hours, after which point I can resolve this issue and push a build.
