### ISSUE TITLE
Veinminer not working on 1.17 server

### ISSUE THREAD

**Issue by Carbuino** [2008Choco/VeinMiner#60]
Hello, I recently downloaded the 1.17.8 of VeinMiner to play on 1.17, however it doesn't seem to work and every time VeinMiner attempts to activate I get this message in the server console.

```
[17:53:00] [Server thread/ERROR]: Could not pass event BlockBreakEvent to VeinMiner v1.17.8
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[Spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[Spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.server.level.PlayerInteractManager.breakBlock(PlayerInteractManager.java:338) ~[Spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:298) ~[Spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:268) ~[Spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1478) ~[Spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(SourceFile:34) ~[Spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(SourceFile:8) ~[Spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[Spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[Spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[Spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[Spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[Spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1124) ~[Spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1117) ~[Spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(SourceFile:110) ~[Spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1100) ~[Spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1030) ~[Spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[Spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoSuchMethodError: 'boolean org.bukkit.entity.Player.breakBlock(org.bukkit.block.Block)'
        at wtf.choco.veinminer.utils.ReflectionUtil.breakBlock(ReflectionUtil.java:52) ~[?:?]
        at wtf.choco.veinminer.listener.BreakBlockListener.onBlockBreak(BreakBlockListener.java:183) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        ... 21 more
```

**Comment by omega9380** [comment]
Try updating to the newest Spigot - mine is at 3124 and VM works great!

**Comment by Carbuino** [comment]
Updated to 3130 and it works now, funny how versions a couple of hours apart can make or break things eh?
