### ISSUE TITLE
1.13.1 error

### ISSUE THREAD

**Issue by KonoromiHimaries** [2008Choco/VeinMiner#7]
logs
```
[08:55:44] [Server thread/WARN]: [VeinMiner] Task #39 for VeinMiner v1.12.0 generated an exception
java.lang.ClassCastException: org.json.simple.JSONObject cannot be cast to com.google.gson.JsonObject
	at wtf.choco.veinminer.utils.metrics.Metrics.submitData(Metrics.java:260) ~[?:?]
	at wtf.choco.veinminer.utils.metrics.Metrics.access$100(Metrics.java:38) ~[?:?]
	at wtf.choco.veinminer.utils.metrics.Metrics$1$1.run(Metrics.java:161) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.1.jar:git-Paper-269]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.13.1.jar:git-Paper-269]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010) ~[patched_1.13.1.jar:git-Paper-269]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:428) ~[patched_1.13.1.jar:git-Paper-269]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:945) ~[patched_1.13.1.jar:git-Paper-269]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:843) ~[patched_1.13.1.jar:git-Paper-269]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
```

timings
```
https://timings.aikar.co/?id=18a3d1b8d7624a99aad7835c705e5a04#plugins
```

**Comment by 2008Choco** [comment]
I'm surprised this hasn't come up before. This is due to Metrics. Worst case scenario, this error shows up every 30 minutes. I'll write a fix soon and release a new version. Thank you
