### ISSUE TITLE
AntiAura incompatible with VeinMiner

### ISSUE THREAD

**Issue by HypixionGaming** [2008Choco/VeinMiner#73]
But i feel this would be better on git

[21:00:50] [Server thread/ERROR]: Error occurred while enabling VeinMiner v1.17.9 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "this.antiAuraApi" is null
	at wtf.choco.veinminer.anticheat.AntiCheatHookAntiAura.<init>(AntiCheatHookAntiAura.java:41) ~[VeinMiner-Bukkit-1.17.9.jar:?]
	at wtf.choco.veinminer.VeinMiner.lambda$onEnable$2(VeinMiner.java:126) ~[VeinMiner-Bukkit-1.17.9.jar:?]
	at wtf.choco.veinminer.VeinMiner.registerAntiCheatHookIfEnabled(VeinMiner.java:380) ~[VeinMiner-Bukkit-1.17.9.jar:?]
	at wtf.choco.veinminer.VeinMiner.onEnable(VeinMiner.java:126) ~[VeinMiner-Bukkit-1.17.9.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[purpur-1.18.jar:git-Purpur-"e65c2e3"]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[purpur-1.18.jar:git-Purpur-"e65c2e3"]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:730) ~[purpur-1.18.jar:git-Purpur-"e65c2e3"]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:506) ~[purpur-1.18.jar:git-Purpur-"e65c2e3"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:347) ~[purpur-1.18.jar:git-Purpur-"e65c2e3"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[purpur-1.18.jar:git-Purpur-"e65c2e3"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.18.jar:git-Purpur-"e65c2e3"]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]

**Comment by HypixionGaming** [comment]
Quote from AA dev "I will have to look into it tomorrow, on the surface I can't see why this is happening; AntiAura's classes and methods seem to be there and VeinMiner is accessing them. The API VeinMiner uses has not changed since 2016 really, as the new AAPI was introduced. (I do really need to sort out the API at some point, but point is nothing should have changed as far as I know). I will look into it more when I have time tomorrow (or maybe the day after)."

**Comment by 2008Choco** [comment]
Thank you for also contacting the AA author. I will reinvestigate and take a look to see why this is causing issues. I don't see any VeinMiner users making use of AntiAura at all (at least through bStats, so that metric may be skewed), though perhaps this is why.
