### ISSUE TITLE
Fabric Crash 1.19.3

### ISSUE THREAD

**Issue by PaladinFallen** [2008Choco/VeinMiner#88]
This error only happen when you press the key for vein miner around the object you are mining.

[09:18:12] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NoSuchMethodError: 'net.minecraft.class_1159 net.minecraft.class_4587$class_4665.method_23761()'
	at wtf.choco.veinminer.VeinMinerMod.lambda$onInitializeClient$7(VeinMinerMod.java:211) ~[veinminer-fabric-2.0.0-mc1.19.jar:?]
	at net.minecraft.class_761.handler$bfj000$beforeClouds(class_761.java:6062) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1505) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1085) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:864) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1193) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:781) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) ~[fabric-loader-0.14.12-1.19.3.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[fabric-loader-0.14.12-1.19.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.12.jar:?]

**Comment by mpab1410** [comment]
@PaladinFallen I went ahead and made a build which contains the fix I made if you want to use it

https://github.com/mpab1410/VeinMiner/releases/tag/2.0.1

**Comment by 2008Choco** [comment]
Thank you for the temporary build @mpab1410 and thanks for the contribution. I've published [an official build on CurseForge](https://www.curseforge.com/minecraft/mc-mods/veinminer-companion/files/4302592) just now, but it has to be approved first. In the meantime, you're welcome to use mpab's build linked above as a mirror.
