### ISSUE TITLE
VeinMiner throws an error when vein mining in a world with WorldGuard disabled

### ISSUE THREAD

**Issue by r521m4** [2008Choco/VeinMiner#97]
When I crouch down as usual and try to destroy the blocks, the following error occurs and I can not destroy them all at once.

Server: spigot-1.20.1 (build in 07/07/'23 20:00)
Plugin: 2.1.0
Java17

↓**errorLog**
```
[20:10:08] [Server thread/ERROR]: Could not pass event BlockBreakEvent to VeinMiner v2.1.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:360) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:319) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:287) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1574) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(SourceFile:42) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(SourceFile:8) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1152) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1131) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1124) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1108) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1019) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.sk89q.worldguard.protection.managers.RegionManager.getApplicableRegions(com.sk89q.worldedit.math.BlockVector3)" because "regionManager" is null
        at wtf.choco.veinminer.integration.WorldGuardIntegration.testFlag(WorldGuardIntegration.java:60) ~[?:?]
        at wtf.choco.veinminer.integration.WorldGuardIntegration.queryFlagVeinMiner(WorldGuardIntegration.java:52) ~[?:?]
        at wtf.choco.veinminer.listener.BreakBlockListener.onBlockBreak(BreakBlockListener.java:115) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor71.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 23 more
```

**Comment by 2008Choco** [comment]
This will happen if WorldGuard is disabled in specific worlds. Minor oversight on my part to not null check here.

**Comment by r521m4** [comment]
Oh I see!
I would like to disable WorldGuard with Plugman and use it!
