### ISSUE TITLE
Error occurred while enabling VeinMiner v2.1.0 (Is it up to date?)

### ISSUE THREAD

**Issue by bameijia** [2008Choco/VeinMiner#99]
[Server thread] w.c.v.VeinMinerPlugin.publish(37): [VeinMiner] Registering commands
2023-07-15 14:23:36,302 [1;31mERROR [Server thread] Minecraft.publish(33): Error occurred while enabling VeinMiner v2.1.0 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at wtf.choco.veinminer.VeinMinerServer.onEnable(VeinMinerServer.java:101) ~[?:?]
	at wtf.choco.veinminer.VeinMinerPlugin.onEnable(VeinMinerPlugin.java:78) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[forge-1.20.1-47.1.21-universal.jar%23166!/:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) ~[forge-1.20.1-47.1.21-universal.jar%23166!/:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:481) ~[forge-1.20.1-47.1.21-universal.jar%23166!/:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:544) ~[forge-1.20.1-47.1.21-universal.jar%23166!/:01aa02eb-b60a95c8c-9ebce8af]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:457) ~[forge-1.20.1-47.1.21-universal.jar%23166!/:01aa02eb-b60a95c8c-9ebce8af]
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:455) ~[server-1.20.1-20230612.114412-srg.jar%23161!/:?]
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:368) ~[server-1.20.1-20230612.114412-srg.jar%23161!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:227) ~[server-1.20.1-20230612.114412-srg.jar%23161!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:855) ~[server-1.20.1-20230612.114412-srg.jar%23161!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:285) ~[server-1.20.1-20230612.114412-srg.jar%23161!/:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalArgumentException: Cannot get key of Legacy Material
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar%23123!/:?]
	at org.bukkit.Material.getKey(Material.java:4487) ~[forge-1.20.1-47.1.21-universal.jar%23166!/:?]
	at wtf.choco.veinminer.platform.BukkitServerPlatform.lambda$getAllBlockTypeKeys$0(BukkitServerPlatform.java:115) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(Unknown Source) ~[?:?]
	at wtf.choco.veinminer.platform.BukkitServerPlatform.getAllBlockTypeKeys(BukkitServerPlatform.java:115) ~[?:?]
	at wtf.choco.veinminer.command.CommandBlocklist.<clinit>(CommandBlocklist.java:20)

**Comment by 2008Choco** [comment]
You are trying to run VeinMiner on a Forge-based server (although I'm unsure which) and I cannot guarantee support on these platforms. There's nothing I can do here to fix this error on startup. VeinMiner does not and cannot support this platform
